# Generated by Django 5.2.11 on 2026-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(max_length=100)),
                ('Emp_Email', models.EmailField(max_length=254)),
                ('Emp_Mobile', models.IntegerField()),
            ],
        ),
    ]
