# Generated by Django 5.2.11 on 2026-02-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Emp_Name',
            new_name='Emp_name',
        ),
    ]
