# Generated by Django 5.2.11 on 2026-02-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_emp_name_employee_emp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField()),
                ('User_Email', models.EmailField(max_length=254)),
                ('User_Mobile', models.IntegerField()),
                ('User_Address', models.CharField(max_length=100)),
            ],
        ),
    ]
