# Generated by Django 5.2.11 on 2026-02-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='User_pass',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_name',
            field=models.CharField(max_length=100),
        ),
    ]
