# Generated by Django 5.2.11 on 2026-03-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_user_user_pass_alter_user_user_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Profile',
        ),
    ]
