# Generated by Django 5.2.11 on 2026-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_rename_user_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btext', models.TextField()),
                ('bdate', models.CharField(max_length=20)),
                ('btime', models.CharField(max_length=20)),
                ('bimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
